export DB_NAME='bp2'
export DB_USER='bp2'
export DB_PASS='y0Wuvk!NRpW2'
export DB_HOST='localhost'
export NLP_URL='http://0.0.0.0'
export GOOGLE_API_KEY='AIzaSyCzJBKLf32DglYjMYmQpHnWNZfhcMjBFNs'
export GOOGLE_APPLICATION_CREDENTIALS='google.creds.json'
